ALTER TABLE VEHICULOS DROP CONSTRAINT FK_VEHICULO_CONDUCTOR;
ALTER TABLE VEHICULOS ADD CONSTRAINT FK_VEHICULO_CONDUCTOR FOREIGN KEY(CECONDUCTOR) REFERENCES CONDUCTORES(CEDULA)ON DELETE CASCADE;
-------------------------------------ACCIONESOK----------------------------------------------------------------------------------------
delete from CONDUCTORES where cedula = 4558237104;
