-----------------------------CARACTERISTICAS-------------------------------------------------------------------------------------
ALTER TABLE Frenos ADD CONSTRAINT CK_FRENOABSTRASERO CHECK (LOWER(FRENOABSTRASERO) in ('si','no'));
ALTER TABLE Frenos ADD CONSTRAINT CK_FRENOABSDELANTERO CHECK (LOWER(FRENOABSDELANTERO) in ('si','no'));
ALTER TABLE Controles ADD CONSTRAINT CK_CONTROL CHECK (LOWER(CONTROLESTABILIDAD) in ('si','no'));
ALTER TABLE AIRBAGS ADD CONSTRAINT CK_AIRBAGFRONTAL CHECK (LOWER(AIRBAGFRONTAL) in ('si','no'));
ALTER TABLE AIRBAGS ADD CONSTRAINT CK_AIRBAGLATERAL CHECK (LOWER(AIRBAGLATERAL) in ('si','no'));
ALTER TABLE AIRBAGS ADD CONSTRAINT CK_AIRBAGCORTINA CHECK (LOWER(AIRBAGCORTINA) in ('si','no'));
ALTER TABLE AIRBAGS ADD CONSTRAINT CK_AIRBAGPOSTERIOR CHECK (LOWER(AIRBAGPOSTERIOR) in ('si','no'));
ALTER TABLE AIRBAGS ADD CONSTRAINT CK_AIRBAGRODILLA CHECK (LOWER(AIRBAGRODILLA) in ('si','no'));
ALTER TABLE AIRBAGS ADD CONSTRAINT CK_AIRBAGCENTRAL CHECK (LOWER(AIRBAGCENTRAL) in ('si','no'));
ALTER TABLE CLASEVEHICULOS ADD CONSTRAINT CK_MODELO_CARACTE CHECK ( MODELO between 1920 and 2019);

-----------------------------VEHICULO--------------------------------------------------------------------------------------------
ALTER TABLE VEHICULOS ADD CONSTRAINT CK_MODELO_CARRO CHECK ( MOCARRO between 1920 and 2019);
ALTER TABLE VEHICULOS ADD CONSTRAINT CK_Placa CHECK (REGEXP_LIKE(Placa,'^[A-Z]{3,3}[0-9]{3,3}+$') or REGEXP_LIKE(Placa,'^[a-z]{3,3}[0-9]{3,3}+$')) ;
ALTER TABLE VEHICULOS ADD CONSTRAINT CK_TSERVICVIO CHECK ( LOWER(TIServicio) IN ('publico','particular', 'diplomaticos','clasicos','carga'));
ALTER TABLE VEHICULOS ADD CONSTRAINT CK_CAPACIDAD CHECK (CAPACIDAD BETWEEN 2 AND 60);
ALTER TABLE VEHICULOS ADD CONSTRAINT CK_CILINDRAJE CHECK (CILINDRAJE BETWEEN 100 AND 10000);
ALTER TABLE VEHICULOS ADD CONSTRAINT CK_COMBUSTIBLE CHECK(LOWER(COMBUSTIBLE)IN('gasolina','gas','eletricidad','diesel','bifuel'));
-----------------------------CONDUCTOR-------------------------------------------------------------------------------------------
ALTER TABLE CONDUCTORES ADD CONSTRAINT CK_T_LICENCIA CHECK(LOWER(TILICENCIA) IN('c1','c2','c3','a1','a2'));
ALTER TABLE CONDUCTORES ADD CONSTRAINT CK_RH CHECK (LOWER(RH)IN('a-','a+','ab+','ab-','b+','b-','o+','o-'));
ALTER TABLE CONDUCTORES ADD CONSTRAINT CK_FECHANACIMIENTO_CONDU CHECK(TO_DATE('01/01/2019','DD/MM/YYYY') -FECHANACIMIENTO >=18); 
ALTER TABLE CONDUCTORES ADD CONSTRAINT  CK_Correo_CONDUC CHECK (REGEXP_LIKE (CORREO, '^(\S+)\@(\S+)\.(\S+)$'));
ALTER TABLE CONDUCTORES ADD CONSTRAINT  CK_LUGARNACIMICONDU CHECK ((not REGEXP_LIKE(LUGARNACIMIENTO,'[0-9]{1,10000}')));
ALTER TABLE CONDUCTORES ADD CONSTRAINT  CK_condu_telefono CHECK ((REGEXP_LIKE(telefono,'^[0-9]{1,1000}+$')) and length(telefono) = 10);
----------------------------ABOGADO----------------------------------------------------------------------------------------------
ALTER TABLE ABOGADOS ADD CONSTRAINT  CK_ABOGADO_telefono CHECK ((REGEXP_LIKE(telefono,'^[0-9]{1,1000}+$')) and length(telefono) = 10);
ALTER TABLE ABOGADOS ADD CONSTRAINT  CK_Correo_ABOGADO CHECK (REGEXP_LIKE (CORREO, '^(\S+)\@(\S+)\.(\S+)$'));








