CREATE TABLE ABOGADO(
IDENTIFICACION NUMBER(10)NOT NULL,
TPROFESIONAL VARCHAR(10)NOT NULL,
NOMBRE VARCHAR(30)NOT NULL,
APELLIDO VARCHAR (30)NOT NULL,
TELEFONO NUMBER(10)NOT NULL,
CORREO VARCHAR(50)NOT NULL);
CREATE TABLE ACCIDENTE(
N_ACCIDENTE NUMBER(4)NOT NULL,
DETALLE VARCHAR (30)NOT NULL,
DETALLEESPE VARCHAR(100)NOT NULL,
VALORARREGLO NUMBER (10,2)NOT NULL,
IABOGADO NUMBER(10)NOT NULL);
CREATE TABLE POLIZA(
NPOLIZA NUMBER(5)NOT NULL,
INICIO_POLIZA DATE NOT NULL,
FIN_POLIZA DATE ,
N_MOTOR NUMBER(10) NOT NULL,
NO_ACCIDENTE NUMBER(4)NOT NULL);

CREATE TABLE VEHICULO(
NO_MOTOR NUMBER(20)NOT NULL,
PLACA VARCHAR(6)NOT NULL,
M_CARRO NUMBER(4)NOT NULL,
T_SERVICIO VARCHAR(30)NOT NULL,
CODIINCIO NUMBER(10)NOT NULL,
CODIFIN NUMBER(10)NOT NULL,
LINEA VARCHAR(30)NOT NULL,
MARCA VARCHAR (30)NOT NULL,
CECONDUCTOR NUMBER(10)NOT NULL,
CAPACIDAD NUMBER(2)NOT NULL,
CILINDRAJE NUMBER(5)NOT NULL,
COMBUSTIBLE VARCHAR(30)NOT NULL); 

CREATE TABLE LOTEPRODUCCION(
CODIGOINICIO NUMBER(10)NOT NULL,
CODIGOFIN NUMBER (10)NOT NULL,
INICIOLOTE DATE NOT NULL,
FINLOTE DATE NOT NULL,
DESCRIPCION VARCHAR(50));
CREATE TABLE CONDUCTOR(
CEDULA NUMBER(10)NOT NULL,
NOMBRE VARCHAR(30)NOT NULL,
APELLIDO VARCHAR (30)NOT NULL,
T_LICENCIA VARCHAR(3)NOT NULL,
NLICENCIA VARCHAR(10)NOT NULL,
RH VARCHAR(3)NOT NULL,
FECHANACIMIENTO DATE NOT NULL,
LUGARNACIMIENTO VARCHAR(20)NOT NULL,
CORREO VARCHAR (50)NOT NULL,
TELEFONO NUMBER(10)NOT NULL);
CREATE TABLE CARACTERISTICA(
LINEA VARCHAR(30)NOT NULL,
MODELO NUMBER(4)NOT NULL);
CREATE TABLE FRENO(
FRENOABSTRASERO VARCHAR (2) NOT NULL,
FRENOABSDELANTERO VARCHAR(2) NOT NULL,
LINEA VARCHAR(30)NOT NULL,
MODELO NUMBER(4)NOT NULL);
CREATE TABLE AIRBAG(
AIRBAGFRONTAL VARCHAR(2)NOT NULL,
AIRBAGLATERAL VARCHAR(2)NOT NULL,
AIRBAGCORTINA VARCHAR (2)NOT NULL,
AIRBAGPOSTERIOR VARCHAR (2)NOT NULL,
AIRBAGRODILLA VARCHAR(2)NOT NULL,
AIRBAGCENTRAL VARCHAR(2)NOT NULL,
LINEA VARCHAR(30)NOT NULL,
MODELO NUMBER(4)NOT NULL);
CREATE TABLE CONTROL(
CONTROLESTABILIDAD VARCHAR(2)NOT NULL,
LINEA VARCHAR(30)NOT NULL,
MODELO NUMBER(4)NOT NULL);
