ALTER TABLE ACCIDENTE ADD CONSTRAINT FK_ACCIDENTE_ABOGADO FOREIGN KEY (IABOGADO) REFERENCES ABOGADO(IDENTIFICACION);
ALTER TABLE POLIZA ADD CONSTRAINT FK_POLIZA_ACCIDENTE FOREIGN KEY(NPOLIZA)REFERENCES ACCIDENTE(N_ACCIDENTE);
ALTER TABLE POLIZA ADD CONSTRAINT FK_POLIZA_VEHICULO FOREIGN KEY(N_MOTOR)REFERENCES VEHICULO(NO_MOTOR);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEHICULO_POLIZA FOREIGN KEY (CODIINCIO,CODIFIN)REFERENCES LOTEPRODUCCION(CODIGOINICIO,CODIGOFIN);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEHICULO_CONDUCTOR FOREIGN KEY(CECONDUCTOR) REFERENCES CONDUCTOR(CEDULA);
ALTER TABLE FRENO ADD CONSTRAINT FK_FRENO_CARACTERISTICAS FOREIGN KEY (LINEA,MODELO)REFERENCES CARACTERISTICA(LINEA,MODELO);
ALTER TABLE AIRBAG ADD CONSTRAINT FK_AIRBAG_CARACTERISTICAS FOREIGN KEY (LINEA,MODELO)REFERENCES CARACTERISTICA(LINEA,MODELO);
ALTER TABLE CONTROL ADD CONSTRAINT FK_CONTROL_CARACTERISTICAS FOREIGN KEY (LINEA,MODELO)REFERENCES CARACTERISTICA(LINEA,MODELO);
ALTER TABLE VEHICULO ADD CONSTRAINT FK_VEHICULO_CARACTERISTICAS FOREIGN KEY (LINEA,M_CARRO)REFERENCES CARACTERISTICA(LINEA,MODELO);

 