ALTER TABLE ABOGADO ADD CONSTRAINT PK_ABOGADO PRIMARY KEY (IDENTIFICACION);
ALTER TABLE ACCIDENTE ADD CONSTRAINT PK_ACCIDENTE PRIMARY KEY (N_ACCIDENTE);
ALTER TABLE POLIZA ADD CONSTRAINT PK_POLIZA PRIMARY KEY (NPOLIZA);
ALTER TABLE VEHICULO ADD CONSTRAINT PK_VEHICULO PRIMARY KEY (NO_MOTOR);
ALTER TABLE LOTEPRODUCCION ADD CONSTRAINT PK_LOTEPRODUCCION PRIMARY KEY (CODIGOINICIO,CODIGOFIN);
ALTER TABLE CONDUCTOR ADD CONSTRAINT PK_CONDUCTOR PRIMARY KEY (CEDULA);
ALTER TABLE CARACTERISTICA ADD CONSTRAINT PK_CARACTERISTICA PRIMARY KEY (LINEA,MODELO);