CREATE TABLE MUSICIAN(
M_NO NUMBER(2)NOT NULL,
M_NAME VARCHAR(30) NOT NULL,
BORN DATE NOT NULL,
DIED DATE,
BORN_IN NUMBER(2) NOT NULL,
LIVING_IN NUMBER(2));

CREATE TABLE PLACE(
PLACE_NO NUMBER(2)NOT NULL,
PLACE_TOWN VARCHAR(30) NOT NULL,
PLACE_COUNTRY VARCHAR(30)NOT NULL);

CREATE TABLE PERFORMER(
PERF_NO NUMBER(2)NOT NULL,
PERF_IS NUMBER(2)NOT NULL,
INSTRUMENT VARCHAR(30)NOT NULL,
PERF_TYPE VARCHAR(30)NOT NULL);

CREATE TABLE COMPOSER(
COMP_NO NUMBER (2)NOT NULL,
COMP_IS NUMBER (2)NOT NULL,
COMP_TYPE VARCHAR(30)NOT NULL);

CREATE TABLE BAND(
BAND_NO NUMBER(2) NOT NULL,
BAND_NAME VARCHAR(30) NOT NULL,
BAND_HOME NUMBER(2) NOT NULL,
BAND_TYPE VARCHAR(30) NOT NULL,
B_DATE DATE,
BAND_CONTACT NUMBER(2) );

CREATE TABLE PLAYS_IN(
PLAYER NUMBER(2)NOT NULL,
BAND_ID NUMBER(2)NOT NULL);

CREATE TABLE COMPOSITION(
C_NO NUMBER(2)NOT NULL,
COMP_DATE DATE,
C_TITLE VARCHAR(30) NOT NULL,
C_IN NUMBER(2));

CREATE TABLE HAS_COMPOSED(
CMPR_NO NUMBER(2) NOT NULL,
CMPN_NO NUMBER(2) NOT NULL );

CREATE TABLE CONCERT(
CONCERT_NO NUMBER(2) NOT NULL,
CONCERT_VENUE VARCHAR(30) NOT NULL,
CONCERT_IN NUMBER(2) NOT NULL,
CON_DATE DATE NOT NULL,
CONCERT_ORGNISER NUMBER(2) NOT NULL );

CREATE TABLE PERFORMANCE(
PFRMNC_NO NUMBER(2) NOT NULL,
GAVE NUMBER(2) NOT NULL, 
PERFORMED NUMBER(2) NOT NULL,
CONDUCTED_BY NUMBER(2) NOT NULL,
PERFORMED_IN NUMBER(2) NOT NULL );