ALTER TABLE BAND ADD CONSTRAINT FK_BAND_PLACE FOREIGN KEY (BAND_HOME)REFERENCES PLACE(PLACE_NO);
ALTER TABLE BAND ADD CONSTRAINT FK_BAND_MUSICIAN FOREIGN KEY (BAND_CONTACT)REFERENCES MUSICIAN(M_NO);
ALTER TABLE COMPOSER ADD CONSTRAINT FK_COMPOSER_MUSICIAN FOREIGN KEY (COMP_IS)REFERENCES MUSICIAN(M_NO);
ALTER TABLE COMPOSITION ADD CONSTRAINT FK_COMPOSITION_PLACE FOREIGN KEY (C_IN) REFERENCES PLACE(PLACE_NO);
ALTER TABLE CONCERT ADD CONSTRAINT FK_CONCERT_MUSICIAN FOREIGN KEY (CONCERT_ORGNISER) REFERENCES MUSICIAN(M_NO);
ALTER TABLE HAS_COMPOSED ADD CONSTRAINT FK_HAS_COMPOSED_COMPOSER FOREIGN KEY (CMPR_NO) REFERENCES COMPOSER(COMP_NO);
ALTER TABLE HAS_COMPOSED ADD CONSTRAINT FK_HAS_COMPOSED_COMPOSITION FOREIGN KEY(CMPN_NO)REFERENCES COMPOSITION(C_NO);
ALTER TABLE MUSICIAN ADD CONSTRAINT FK_MUSICIAN_PLACE FOREIGN KEY(BORN_IN)REFERENCES PLACE(PLACE_NO);
ALTER TABLE MUSICIAN ADD CONSTRAINT FK_MUSICIAN_PLACELIVING FOREIGN KEY(LIVING_IN)REFERENCES PLACE(PLACE_NO);
ALTER TABLE PERFORMANCE ADD CONSTRAINT FK_PERFORMANCE_BAND FOREIGN KEY(GAVE) REFERENCES BAND(BAND_NO);
ALTER TABLE PERFORMANCE ADD CONSTRAINT FK_PERFORMANCE_COMPOSITION FOREIGN KEY(PERFORMED) REFERENCES COMPOSITION(C_NO);
ALTER TABLE PERFORMANCE ADD CONSTRAINT FK_PERFORMANCE_MUSICIAN FOREIGN KEY (CONDUCTED_BY) REFERENCES MUSICIAN(M_NO);
ALTER TABLE PERFORMANCE ADD CONSTRAINT FK_PERFORMANCE_CONCERT FOREIGN KEY (PERFORMED_IN) REFERENCES CONCERT(CONCERT_NO);
ALTER TABLE PERFORMER ADD CONSTRAINT FK_PERFORMER_MUSICIAN FOREIGN KEY (PERF_IS) REFERENCES MUSICIAN (M_NO);
ALTER TABLE PLAYS_IN ADD CONSTRAINT FK_PLAYS_IN_PERFORMER FOREIGN KEY (PLAYER) REFERENCES PERFORMER(PERF_NO);
ALTER TABLE PLAYS_IN ADD CONSTRAINT FK_PLAYS_IN_BAND FOREIGN KEY (BAND_ID) REFERENCES BAND(BAND_NO);

