CREATE TABLE Abogados(
Identificacion NUMBER(10)NOT NULL,
TarProfesional VARCHAR(10)NOT NULL,
Nombre VARCHAR(30)NOT NULL,
Apellido VARCHAR (30)NOT NULL,
Telefono NUMBER(10)NOT NULL,
Correo VARCHAR(50)NOT NULL);

CREATE TABLE Accidentes(
NoAccidente NUMBER(4)NOT NULL,
Detalle VARCHAR (30)NOT NULL,
DetalleEspe VARCHAR(100)NOT NULL,
ValorArreglo NUMBER (10,2)NOT NULL,
IdAbogado NUMBER(10)NOT NULL);

CREATE TABLE Polizas(
NoPoliza NUMBER(5)NOT NULL,
InicioPoliza DATE NOT NULL,
FinPoliza DATE,
NoMotor NUMBER(10) NOT NULL,
NoAccidente NUMBER(4)NOT NULL);

CREATE TABLE Vehiculos(
NoMotor NUMBER(20)NOT NULL,
Placa VARCHAR(6)NOT NULL,
MoCarro NUMBER(4)NOT NULL,
TiServicio VARCHAR(30)NOT NULL,
CodiInicio NUMBER(10)NOT NULL,
CodiFin NUMBER(10)NOT NULL,
Linea VARCHAR(30)NOT NULL,
Marca VARCHAR (30)NOT NULL,
CeConductor NUMBER(10)NOT NULL,
Capacidad NUMBER(2)NOT NULL,
Cilindraje NUMBER(5)NOT NULL,
Combustible VARCHAR(30)NOT NULL); 

CREATE TABLE LoteProduccion(
CodigoInicio NUMBER(10)NOT NULL,
CodigoFin NUMBER (10)NOT NULL,
InicioLote DATE NOT NULL,
FinLote DATE NOT NULL,
Descripcion VARCHAR(50));

CREATE TABLE Conductores(
Cedula NUMBER(10)NOT NULL,
Nombre VARCHAR(30)NOT NULL,
Apellido VARCHAR (30)NOT NULL,
TiLicencia VARCHAR(3)NOT NULL,
NoLicencia VARCHAR(10)NOT NULL,
Rh VARCHAR(3)NOT NULL,
FechaNacimiento DATE NOT NULL,
LugarNacimiento VARCHAR(20)NOT NULL,
Correo VARCHAR (50)NOT NULL,
Telefono NUMBER(10)NOT NULL);

CREATE TABLE Caracteristicas(
id NUMBER (4)NOT NULL);

CREATE TABLE CLASEVEHICULOS(
Linea VARCHAR(30)NOT NULL,
Modelo NUMBER(4)NOT NULL,
IdCarac NUMBER (4)NOT NULL);

CREATE TABLE Frenos(
FrenoAbsTrasero VARCHAR (2) NOT NULL,
FrenoAbsDelantero VARCHAR(2) NOT NULL,
IdCarac NUMBER(4));

CREATE TABLE Airbags(
AirbagFrontal VARCHAR(2)NOT NULL,
AirbagLateral VARCHAR(2)NOT NULL,
AirbagCortina VARCHAR (2)NOT NULL,
AirbagPosterior VARCHAR (2)NOT NULL,
AirbagRodilla VARCHAR(2)NOT NULL,
AirbagCentral VARCHAR(2)NOT NULL,
IdCarac NUMBER(4)NOT NULL);

CREATE TABLE Controles(
ControlEstabilidad VARCHAR(2)NOT NULL,
IdCarac NUMBER(4)NOT NULL);
