CREATE OR REPLACE PACKAGE BODY PA_VENDEDOR IS
    PROCEDURE AD_POLIZAS(xFINPOLIZA IN DATE,xNOMOTOR IN NUMBER,xNOACCIDENTE IN NUMBER)IS
    BEGIN
        PC_POLIZAS.AD_POLIZAS(xFINPOLIZA,xNOMOTOR,xNOACCIDENTE);
    COMMIT;
    EXCEPTION 
    WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20038,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    PROCEDURE AD_VEHICULOS(xNOMOTOR IN NUMBER,xPLACA IN VARCHAR,xMOCARRO IN NUMBER,xTISERVICIO IN VARCHAR,xCODIINICIO IN NUMBER,xCODIFIN IN NUMBER,xLINEA IN VARCHAR,xMARCA IN VARCHAR,xCECONDUCTOR IN NUMBER,xCAPACIDAD IN NUMBER,xCILINDRAJE IN NUMBER,xCOMBUSTIBLE IN VARCHAR)IS
    BEGIN
        PC_VEHICULOS.AD_VEHICULOS(xNOMOTOR,xPLACA,xMOCARRO,xTISERVICIO,xCODIINICIO,xCODIFIN,xLINEA,xMARCA,xCECONDUCTOR,xCAPACIDAD,xCILINDRAJE,xCOMBUSTIBLE);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20040,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    PROCEDURE AD_CONDUCTORES(xCedula IN NUMBER,xNOMBRE IN VARCHAR,xApellido IN VARCHAR,xTiLicencia IN VARCHAR, xNoLicencia IN NUMBER,xRh IN NUMBER,xFechaNacimiento IN DATE,xLugarNacimiento IN VARCHAR,xCorreo IN VARCHAR,xTelefono IN NUMBER,xPasivo IN NUMBER,xActivo IN NUMBER)IS
    BEGIN 
        PC_VEHICULOS.AD_CONDUCTORES(xCEDULA,xNOMBRE,xAPELLIDO,xTILICENCIA,xNOLICENCIA,xRH,xFECHANACIMIENTO,xLUGARNACIMIENTO,xCORREO,xTELEFONO,xPASIVO,xACTIVO);
    COMMIT;
    EXCEPTION 
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20041,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    PROCEDURE AD_ACCIDENTES(xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER, xIdAbogado IN NUMBER,xFecha IN DATE,xDetalleXml IN XMLTYPE)IS
    BEGIN 
        PC_ACCIDENTES.AD_ACCIDENTES(xDETALLE,xDETALLEESPE,xVALORARREGLO,xIDABOGADO,xFECHA,xDETALLEXML);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20042,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    PROCEDURE MOD_ACCIDENTES(xNoAccidente IN NUMBER,xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER,xDetalleXml IN XMLTYPE)IS 
    BEGIN
        PC_ACCIDENTES.MOD_ACCIDENTES(xNOACCIDENTE,xDETALLE,xDETALLEESPE,xVALORARREGLO,xDETALLEXML);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20045,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    PROCEDURE MOD_POLIZAS(xNOPOLIZA IN NUMBER,xFINPOLIZA IN DATE)IS
    BEGIN
        PC_POLIZAS.MOD_POLIZAS(xNOPOLIZA,xFINPOLIZA);
    COMMIT;
    EXCEPTION 
    WHEN OTHERS THEN
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20039,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    PROCEDURE MOD_VEHICULOS(xNOMOTOR IN NUMBER,xCECONDUCTOR IN NUMBER)IS
    BEGIN 
        PC_VEHICULOS.MOD_VEHICULOS(xNOMOTOR,xCECONDUCTOR);
    COMMIT;
    EXCEPTION 
    WHEN OTHERS THEN 
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20042,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    PROCEDURE MOD_CONDUCTORES(xCedula IN NUMBER,xCorreo IN VARCHAR,xTelefono IN NUMBER)IS
    BEGIN
        PC_VEHICULOS.MOD_CONDUCTORES(xCEDULA,xCORREO,xTELEFONO);
        COMMIT;
    EXCEPTION 
    WHEN OTHERS THEN 
    ROLLBACK;
    RAISE_APPLICATION_ERROR(-20043,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    FUNCTION CO_POLIZAS RETURN SYS_REFCURSOR IS CON_POLIZAS SYS_REFCURSOR;
		BEGIN
			CON_POLIZAS := PC_POLIZAS.CO_POLIZAS;
		RETURN CON_POLIZAS;
	END;
    FUNCTION CO_VEHICULOS RETURN SYS_REFCURSOR IS CON_VEHICULOS SYS_REFCURSOR;
		BEGIN
			CON_VEHICULOS := PC_VEHICULOS.CO_VEHICULOS;
		RETURN CON_VEHICULOS;
	END;
    FUNCTION CO_CONDUCTORES RETURN SYS_REFCURSOR IS CON_CONDUCTORES SYS_REFCURSOR;
		BEGIN
			CON_CONDUCTORES := PC_VEHICULOS.CO_CONDUCTORES;
		RETURN CON_CONDUCTORES;
	END;
    FUNCTION CO_ACCIDENTES RETURN SYS_REFCURSOR IS CON_ACCIDENTES SYS_REFCURSOR;
		BEGIN
			CON_ACCIDENTES := PC_ACCIDENTES.CO_ACCIDENTES;
		RETURN CON_ACCIDENTES;
	END;
END PA_VENDEDOR;
/

CREATE OR REPLACE PACKAGE BODY PA_ADMINISTRADOR IS
    PROCEDURE AD_ACCIDENTES(xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER, xIdAbogado IN NUMBER,xFecha IN DATE,xDetalleXml IN XMLTYPE)IS
    BEGIN 
        PC_ACCIDENTES.AD_ACCIDENTES(xDETALLE,xDETALLEESPE,xVALORARREGLO,xIDABOGADO,xFECHA,xDETALLEXML);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20042,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    
    PROCEDURE MOD_ACCIDENTES(xNoAccidente IN NUMBER,xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER,xDetalleXml IN XMLTYPE)IS 
    BEGIN
        PC_ACCIDENTES.MOD_ACCIDENTES(xNOACCIDENTE,xDETALLE,xDETALLEESPE,xVALORARREGLO,xDETALLEXML);
    COMMIT;
    EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20046,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
    END;
    FUNCTION CO_ACCIDENTES RETURN SYS_REFCURSOR IS CON_ACCIDENTES SYS_REFCURSOR;
		BEGIN
			CON_ACCIDENTES := PC_ACCIDENTES.CO_ACCIDENTES;
		RETURN CON_ACCIDENTES;
	END;
END PA_ADMINISTRADOR;
