CREATE OR REPLACE PACKAGE PA_VENDEDOR IS 
    PROCEDURE AD_POLIZAS(xFINPOLIZA IN DATE,xNOMOTOR IN NUMBER,xNOACCIDENTE IN NUMBER);
    PROCEDURE AD_VEHICULOS(xNOMOTOR IN NUMBER,xPLACA IN VARCHAR,xMOCARRO IN NUMBER,xTISERVICIO IN VARCHAR,xCODIINICIO IN NUMBER,xCODIFIN IN NUMBER,xLINEA IN VARCHAR,xMARCA IN VARCHAR,xCECONDUCTOR IN NUMBER,xCAPACIDAD IN NUMBER,xCILINDRAJE IN NUMBER,xCOMBUSTIBLE IN VARCHAR);
    PROCEDURE AD_CONDUCTORES(xCedula IN NUMBER,xNOMBRE IN VARCHAR,xApellido IN VARCHAR,xTiLicencia IN VARCHAR, xNoLicencia IN NUMBER,xRh IN NUMBER,xFechaNacimiento IN DATE,xLugarNacimiento IN VARCHAR,xCorreo IN VARCHAR,xTelefono IN NUMBER,xPasivo IN NUMBER,xActivo IN NUMBER);
    PROCEDURE AD_ACCIDENTES(xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER, xIdAbogado IN NUMBER,xFecha IN DATE,xDetalleXml IN XMLTYPE);
    PROCEDURE MOD_POLIZAS(xNOPOLIZA IN NUMBER,xFINPOLIZA IN DATE);
    PROCEDURE MOD_VEHICULOS(xNOMOTOR IN NUMBER,xCECONDUCTOR IN NUMBER);
    PROCEDURE MOD_CONDUCTORES(xCedula IN NUMBER,xCorreo IN VARCHAR,xTelefono IN NUMBER);
    PROCEDURE MOD_ACCIDENTES(xNoAccidente IN NUMBER,xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER,xDetalleXml IN XMLTYPE);
    FUNCTION CO_POLIZAS RETURN SYS_REFCURSOR;    
    FUNCTION CO_CONDUCTORES RETURN SYS_REFCURSOR;
    FUNCTION CO_VEHICULOS RETURN SYS_REFCURSOR;
    FUNCTION CO_ACCIDENTES RETURN SYS_REFCURSOR;
END PA_VENDEDOR;
/
CREATE OR REPLACE PACKAGE PA_ADMINISTRADOR IS
    PROCEDURE AD_ACCIDENTES(xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER, xIdAbogado IN NUMBER,xFecha IN DATE,xDetalleXml IN XMLTYPE);
    PROCEDURE MOD_ACCIDENTES(xNoAccidente IN NUMBER,xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER,xDetalleXml IN XMLTYPE);
    FUNCTION CO_ACCIDENTES RETURN SYS_REFCURSOR;
END PA_ADMINISTRADOR;
/