CREATE OR REPLACE PACKAGE PC_ABOGADOS IS
    PROCEDURE AD_ABOGADOS(xIDENTIFICACION IN NUMBER,xTARPROFESIONAL IN NUMBER,xNOMBRE VARCHAR,xAPELLIDO IN VARCHAR,xTELEFONO IN NUMBER,xCORREO IN VARCHAR);
    PROCEDURE MOD_ABOGADOS(xIDENTIFICACION IN NUMBER,xTELEFONO IN NUMBER,xCORREO IN VARCHAR);
    FUNCTION CO_ABOGADOS RETURN SYS_REFCURSOR;
END PC_ABOGADOS;
/
CREATE OR REPLACE PACKAGE PC_ACCIDENTES IS
    PROCEDURE AD_ACCIDENTES(xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER, xIdAbogado IN NUMBER,xFecha IN DATE,xDetalleXml IN XMLTYPE);
    PROCEDURE MOD_ACCIDENTES(xNoAccidente IN NUMBER,xDetalle IN VARCHAR,xDetalleEspe IN VARCHAR,xValorArreglo IN NUMBER,xDetalleXml IN XMLTYPE);
    FUNCTION CO_ACCIDENTES RETURN SYS_REFCURSOR;
END PC_ACCIDENTES;
/
CREATE OR REPLACE PACKAGE PC_POLIZAS IS
    PROCEDURE AD_POLIZAS(xFinpoliza IN DATE,xNoMotor IN NUMBER,xNoAccidente IN NUMBER);
    PROCEDURE MOD_POLIZAS(xNoPoliza IN NUMBER,xFinPoliza IN DATE);
    FUNCTION CO_POLIZAS RETURN SYS_REFCURSOR;
END PC_POLIZAS;
/
CREATE OR REPLACE PACKAGE PC_VEHICULOS IS
    PROCEDURE AD_VEHICULOS(xNOMOTOR IN NUMBER,xPLACA IN VARCHAR,xMOCARRO IN NUMBER,xTISERVICIO IN VARCHAR,xCODIINICIO IN NUMBER,xCODIFIN IN NUMBER,xLINEA IN VARCHAR,xMARCA IN VARCHAR,xCECONDUCTOR IN NUMBER,xCAPACIDAD IN NUMBER,xCILINDRAJE IN NUMBER,xCOMBUSTIBLE IN VARCHAR);
    PROCEDURE AD_CONDUCTORES(xCedula IN NUMBER,xNOMBRE IN VARCHAR,xApellido IN VARCHAR,xTiLicencia IN VARCHAR, xNoLicencia IN NUMBER,xRh IN NUMBER,xFechaNacimiento IN DATE,xLugarNacimiento IN VARCHAR,xCorreo IN VARCHAR,xTelefono IN NUMBER,xPasivo IN NUMBER,xActivo IN NUMBER);
    PROCEDURE MOD_VEHICULOS(xNOMOTOR IN NUMBER,xCECONDUCTOR IN NUMBER);
    PROCEDURE MOD_CONDUCTORES(xCedula IN NUMBER,xCorreo IN VARCHAR,xTelefono IN NUMBER);
    FUNCTION CO_VEHICULOS RETURN SYS_REFCURSOR;
    FUNCTION CO_CONDUCTORES RETURN SYS_REFCURSOR;
END PC_VEHICULOS;
/