CREATE OR REPLACE PACKAGE BODY PC_ABOGADOS IS
    PROCEDURE AD_ABOGADOS(xIDENTIFICACION IN NUMBER,xTARPROFESIONAL IN NUMBER,xNOMBRE VARCHAR,xAPELLIDO IN VARCHAR,xTELEFONO IN NUMBER,xCORREO IN VARCHAR)IS
        BEGIN
            INSERT INTO ABOGADOS(IDENTIFICACION,TARPROFESIONAL,NOMBRE,APELLIDO,TELEFONO,CORREO)VALUES(xIDENTIFICACION,xTARPROFESIONAL,xNOMBRE,xAPELLIDO,xTELEFONO,xCORREO);
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20020,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
        END;
    PROCEDURE MOD_ABOGADOS(xIDENTIFICACION IN NUMBER,xTELEFONO IN NUMBER,xCORREO IN VARCHAR)IS
        BEGIN
            UPDATE ABOGADOS SET TELEFONO=xTELEFONO,CORREO=xCORREO WHERE IDENTIFICACION=xIDENTIFICACION;
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20021,'se encontro un error - '||SQLCODE||'-ERROR-'||SQLERRM);
        END;
    FUNCTION CO_ABOGADOS RETURN SYS_REFCURSOR IS CO_ER SYS_REFCURSOR;
    BEGIN 
    OPEN CO_ER FOR
        SELECT * FROM ABOGADOS;
    RETURN CO_ER;
    END;
END PC_ABOGADOS;
/
