/*Seguridad*/
/*Crear roles*/
CREATE ROLE R_VENDEDOR;
CREATE ROLE R_ADMINISTRADOR;

/*Otorgar Permisos a los actores.*/
GRANT EXECUTE ON PA_VENDEDOR TO R_VENDEDOR;
GRANT EXECUTE ON PA_ADMINISTRADOR TO R_ADMINISTRADOR;



/*Otorgar permisos a los carnets para se el Auxiliar Operativo*/
GRANT EXECUTE ON PA_AUXILIAR_OPERATIVO TO BD2113421;
GRANT EXECUTE ON PA_ADMINISTRADOR TO bd2145059;