/*Eliminar roles*/
DROP ROLE R_VENDEDOR;
DROP ROLE R_ADMINISTRADOR;

/*Quitar permisos a los actores.*/
REVOKE EXECUTE ON PA_VENDEDOR FROM R_VENDEDOR;
REVOKE EXECUTE ON PA_ADMINISTRADOR FROM R_ADMINISTRADOR;
