ALTER TABLE Abogados ADD CONSTRAINT UK_ABOGADO UNIQUE (TarProfesional);
ALTER TABLE Vehiculos ADD CONSTRAINT UK_VEHICULO UNIQUE (PLACA);
ALTER TABLE Conductores ADD CONSTRAINT UK_CORREO_CONDUCTOR UNIQUE (CORREO);
ALTER TABLE Conductores ADD CONSTRAINT UK_TELEFONO_CONDUCTOR UNIQUE (TELEFONO);
ALTER TABLE Abogados ADD CONSTRAINT UK_TELFONO_ABOGADO UNIQUE (TELEFONO);
ALTER TABLE Abogados ADD CONSTRAINT UK_CORREO_ABOGADO UNIQUE (CORREO);