--------------------PARTICIPA----------------------------------------------
INSERT INTO PARTICIPA(IDMIEMBRO,NOMBREVERSION)VALUES(1,'TOURFRANCIA 2019');
INSERT INTO PARTICIPA(IDMIEMBRO,NOMBREVERSION)VALUES(2,'TOURFRANCIA 2019');
INSERT INTO PARTICIPA(IDMIEMBRO,NOMBREVERSION)VALUES(3,'TOURFRANCIA 2019');
--------------------PROPIEDADDE----------------------------------------------
INSERT INTO PROPIEDADDE(PORCENTAJE,CODIGOCA,IDMIEMBRO)VALUES(50,'1CA',1);
INSERT INTO PROPIEDADDE(PORCENTAJE,CODIGOCA,IDMIEMBRO)VALUES(40,'4CA',2);
INSERT INTO PROPIEDADDE(PORCENTAJE,CODIGOCA,IDMIEMBRO)VALUES(90,'14CA',3);
--------------------CARRERA--------------------------------------------------
INSERT INTO CARRERA(CODIGO,NOMBRE,PAIS,CATEGORIA,PERIODICIDAD,NOMBREVERSION)VALUES(1,'TOUR F','FRANCIA','PROFESIONAL','1 SEMESTRE', '20191');
INSERT INTO CARRERA(CODIGO,NOMBRE,PAIS,CATEGORIA,PERIODICIDAD,NOMBREVERSION)VALUES(4,'VUELTA A ESPAÑA','ESPAÑA','PROFESIONAL','1 SEMESTRE', '20191');
INSERT INTO CARRERA(CODIGO,NOMBRE,PAIS,CATEGORIA,PERIODICIDAD,NOMBREVERSION)VALUES(14,'VUELTA A COLOMBIA','COLOMBIA','PROFESIONAL','1 SEMESTRE', '20191');
-------------------PUNTO-----------------------------------------------------
INSERT INTO PUNTO (ORDEN,NOMBRE,TIPO,DISTANCIA,TIEMPOLIMITE,CODIGOCA,NOMBRESEGMENTO)VALUES(10,'PUNTO 3','MONTAÑA',15,TO_DATE('01:05:25','HH:MM:SS'),1,'LA CUCHILLA' );
INSERT INTO PUNTO (ORDEN,NOMBRE,TIPO,DISTANCIA,TIEMPOLIMITE,CODIGOCA,NOMBRESEGMENTO)VALUES(8,'PUNTO 5','PLANO',25,TO_DATE('01:05:25','HH:MM:SS'),4,'RELAMPAGO' );
INSERT INTO PUNTO (ORDEN,NOMBRE,TIPO,DISTANCIA,TIEMPOLIMITE,CODIGOCA,NOMBRESEGMENTO)VALUES(18,'PUNTO 7','MONTAÑA',35,TO_DATE('04:11:48','HH:MM:SS'),14,'NICO' );
------------------ORGANIZADO------------------------------------------------
INSERT INTO ORGANIZADO (RAZONSOCIAL,NOMBREVERSION)VALUES('MOVISTAR','20191');
INSERT INTO ORGANIZADO (RAZONSOCIAL,NOMBREVERSION)VALUES('COMCEL','20191');
INSERT INTO ORGANIZADO (RAZONSOCIAL,NOMBREVERSION)VALUES('CLARO','20191');
------------------FOTOS-----------------------------------------------------
INSERT INTO FOTO (NUMEROREGISTRO,FOTO) VALUES (12,'MONTAÑA.PNG');
INSERT INTO FOTO (NUMEROREGISTRO,FOTO) VALUES (15,'PLANO.PNG');
INSERT INTO FOTO (NUMEROREGISTRO,FOTO) VALUES (18,'MIXTO.JPG');
------------------REGISTRO----------------------------------------------------
INSERT INTO REGISTRO (NUMERO,FECHA,TIEMPO,POSICION,REVISION,DIFICULTAD,FOTO,COMENTARIO) VALUES (200,TO_DATE('2017-05-14','YYYY-MM-DD'),TO_DATE('01:05:25','HH:MM:SS'),1,'BIEN','NORMAL','MONTAÑA.PNG','NO HUBO ACCIDENTES');
INSERT INTO REGISTRO (NUMERO,FECHA,TIEMPO,POSICION,REVISION,DIFICULTAD,FOTO,COMENTARIO) VALUES (250,TO_DATE('2017-05-14','YYYY-MM-DD'),TO_DATE('01:05:25','HH:MM:SS'),1,'BIEN','NORMAL','MONTAÑA.PNG','NO HUBO ACCIDENTES');
INSERT INTO REGISTRO (NUMERO,FECHA,TIEMPO,POSICION,REVISION,DIFICULTAD,FOTO,COMENTARIO) VALUES (340,TO_DATE('2017-05-14','YYYY-MM-DD'),TO_DATE('01:05:25','HH:MM:SS'),1,'BIEN','NORMAL','MONTAÑA.PNG','NO HUBO ACCIDENTES');
------------------SEGMENTO----------------------------------------------------
INSERT INTO SEGMENTO (NOMBRE,TIPO,NUMEROREGISTRO)VALUES('ETAPA 1','MONTAÑA',200);
INSERT INTO SEGMENTO (NOMBRE,TIPO,NUMEROREGISTRO)VALUES('ETAPA 4','RUTA',250);
INSERT INTO SEGMENTO (NOMBRE,TIPO,NUMEROREGISTRO)VALUES('ETAPA 6','MIXTO',340);
------------------VERSION----------------------------------------------------
INSERT INTO VERSION (NOMBRE,FECHA,NOMBRESEGMENTO,ID_MIEMBRO)VALUES('20191',TO_DATE('2012-06-24','YYYY-MM-DD'),'ETAPA 1',471);
INSERT INTO VERSION (NOMBRE,FECHA,NOMBRESEGMENTO,ID_MIEMBRO)VALUES('20201',TO_DATE('2012-06-24','YYYY-MM-DD'),'ETAPA 1',471);
INSERT INTO VERSION (NOMBRE,FECHA,NOMBRESEGMENTO,ID_MIEMBRO)VALUES('20211',TO_DATE('2012-06-24','YYYY-MM-DD'),'ETAPA 1',471);
------------------CICLISTA---------------------------------------------------
INSERT INTO CICLISTA(NACIMIENTO,CATEGORIA,IDMIEMBRO,NUMEROREGISTRO)VALUES(TO_DATE('27/02/2000','DD/MM/YYYY'),'PROFESIONAL',12,78);
INSERT INTO CICLISTA(NACIMIENTO,CATEGORIA,IDMIEMBRO,NUMEROREGISTRO)VALUES(TO_DATE('27/02/2000','DD/MM/YYYY'),'PROFESIONAL',12,78);
INSERT INTO CICLISTA(NACIMIENTO,CATEGORIA,IDMIEMBRO,NUMEROREGISTRO)VALUES(TO_DATE('27/02/2000','DD/MM/YYYY'),'PROFESIONAL',12,78);
------------------PERSONA----------------------------------------------------
INSERT INTO PERSONA(NOMBRE,IDMIEMBRO,RAZONSOCIAL)VALUES('SANTIAGO LAITON',78,'COLPATRIA');
INSERT INTO PERSONA(NOMBRE,IDMIEMBRO,RAZONSOCIAL)VALUES('SANTIAGO LAITON',78,'COLPATRIA');
INSERT INTO PERSONA(NOMBRE,IDMIEMBRO,RAZONSOCIAL)VALUES('SANTIAGO LAITON',78,'COLPATRIA');
-----------------MIEMBRO------------------------------------------------------
INSERT INTO MIEMBRO(ID,IDT,IDN,PAIS,CORREO)VALUES(788,'CC',1001169364,'COLOMBIA','SAAGULAICU@HOTMAIL.COM');
INSERT INTO MIEMBRO(ID,IDT,IDN,PAIS,CORREO)VALUES(788,'CC',1001169364,'COLOMBIA','SAAGULAICU@HOTMAIL.COM');
INSERT INTO MIEMBRO(ID,IDT,IDN,PAIS,CORREO)VALUES(788,'CC',1001169364,'COLOMBIA','SAAGULAICU@HOTMAIL.COM');
----------------EMPRESA-------------------------------------------------------
INSERT INTO EMPRESA(RAZONSOCIAL,IDMIEMBRO)VALUES('COMSILAS.A.S',78);
INSERT INTO EMPRESA(RAZONSOCIAL,IDMIEMBRO)VALUES('COMSILAS.A.S',78);
INSERT INTO EMPRESA(RAZONSOCIAL,IDMIEMBRO)VALUES('COMSILAS.A.S',78);