INSERT INTO PARTICIPA(IDMIEMBRO,NOMBREVERSION)VALUES('1','TOURFRANCIA 2019');
INSERT INTO CARRERA(CODIGO,NOMBRE,PAIS,CATEGORIA,PERIODICIDAD,NOMBREVERSION)VALUES(1,'TOUR F','FRANCIA',2345,'1 SEMESTRE', '20191');
INSERT INTO FOTO (NUMEROREGISTRO,FOTO) VALUES (2,5);
INSERT INTO SEGMENTO (NOMBRE,TIPO,NUMEROREGISTRO)VALUES('ETAPA 6','MIXTO','340');
INSERT INTO CICLISTA(NACIMIENTO,CATEGORIA,IDMIEMBRO,NUMEROREGISTRO)VALUES(TO_DATE('27/02/2000','DD/MM/YYYY'),412,12,78);
