--------------------------------CK---------------------------------------------------------------
--------------------------------MIEMBRO---------------------------------------------------------------
ALTER TABLE MIEMBRO ADD CONSTRAINT CK_MIEMBRO_ID CHECK (ID BETWEEN 1 AND 99999);
ALTER TABLE MIEMBRO ADD CONSTRAINT CK_MIEMBRO_IDT CHECK (IDT IN ('CC','NT','CE'));
ALTER TABLE MIEMBRO ADD CONSTRAINT CK_MIEMBRO_NID CHECK (LENGTH(IDN)>=15);
ALTER TABLE MIEMBRO ADD CONSTRAINT CK_MIEMRO_CORREO CHECK (REGEXP_LIKE(CORREO,'^(\S+)\@(\S+)\.(\S+)$'));
ALTER TABLE MIEMBRO ADD CONSTRAINT CK_MIEMBRO_PAIS CHECK (REGEXP_LIKE(PAIS,'^[A-Z]{1,15}+$'));
--------------------------------PERSONA---------------------------------------------------------------
ALTER TABLE PERSONA ADD CONSTRAINT CK_PERSONA_IDMIEMBRO CHECK (IDMIEMBRO BETWEEN 1 AND 99999);
--------------------------------EMPRESA---------------------------------------------------------------
ALTER TABLE EMPRESA ADD CONSTRAINT CK_EMPRESA_IDMIEMBRO CHECK (IDMIEMBRO BETWEEN 1 AND 99999);
--------------------------------CICLISTA---------------------------------------------------------------
ALTER TABLE CICLISTA ADD CONSTRAINT CK_CICLISTA_IDMIEMBRO CHECK (IDMIEMBRO BETWEEN 1 AND 99999);
ALTER TABLE CICLISTA ADD CONSTRAINT CK_CICLISTA_CATEGORIA CHECK (CATEGORIA BETWEEN 1 AND 5);
ALTER TABLE CICLISTA ADD CONSTRAINT CK_CICLISTA_NREGISTRO CHECK (NUMEROREGISTRO BETWEEN 1 AND 99999);
--------------------------------PROPIEDADDE---------------------------------------------------------------
ALTER TABLE PROPIEDADDE ADD CONSTRAINT CK_PROPIEDADDE_IDMIEMBRO CHECK (IDMIEMBRO BETWEEN 1 AND 99999);
--------------------------------REGISTRO---------------------------------------------------------------
ALTER TABLE REGISTRO ADD CONSTRAINT CK_CICLISTA_NUMEROREGISTRO CHECK (NUMERO BETWEEN 1 AND 99999);
ALTER TABLE REGISTRO ADD CONSTRAINT CK_REGISTRO_TIEMPO CHECK (LENGTH(TIEMPO)>=9 AND TIEMPO>0);
ALTER TABLE REGISTRO ADD CONSTRAINT CK_REGISTRO_DIFICULTAD CHECK (DIFICULTAD IN('A','M','B'));
ALTER TABLE REGISTRO ADD CONSTRAINT CK_REGISTRO_FOTO CHECK (FOTO LIKE 'www.%' AND FOTO LIKE'%.PDF' OR FOTO LIKE'%.GIF');
--------------------------------FOTO--------------------------------------------------------------------
ALTER TABLE FOTO ADD CONSTRAINT CK_FOTO_NUMEROREGISTRO CHECK (NUMEROREGISTRO BETWEEN 1 AND 99999);
ALTER TABLE FOTO ADD CONSTRAINT CK_FOTO_FOTO CHECK (FOTO LIKE 'www.%' AND FOTO LIKE'%.PDF' OR FOTO LIKE'%.GIF');
--------------------------------PUNTO----------------------------------------------------------------------------------------
ALTER TABLE PUNTO ADD CONSTRAINT CK_PUNTO_CODIGO CHECK (REGEXP_LIKE(CODIGOCA,'[0-9]{3,3}[A-Z]{17,17}+$')AND LENGTH(CODIGOCA)=20);
ALTER TABLE PUNTO ADD CONSTRAINT CK_REGISTRO_TIEMPOCA CHECK (LENGTH(TIEMPOLIMITE)>=9 AND TIEMPOLIMITE>0);
ALTER TABLE PUNTO ADD CONSTRAINT CK_PUNTO_TIPO CHECK (TIPO IN('P','L','H','A','M','V','C'));
--------------------------------CARRERA--------------------------------------------------------------------------------------
ALTER TABLE CARRERA ADD CONSTRAINT CK_CARRERA_CODIGO CHECK (REGEXP_LIKE(CODIGO,'[0-9]{3,3}[A-Z]{17,17}+$')AND LENGTH(CODIGO)=20);
ALTER TABLE CARRERA ADD CONSTRAINT CK_CARRERA_PAIS CHECK (REGEXP_LIKE(PAIS,'^[A-Z]{1,15}+$'));
ALTER TABLE CARRERA ADD CONSTRAINT CK_CARRERA_CATEGORIA CHECK (CATEGORIA BETWEEN 1 AND 5);
ALTER TABLE CARRERA ADD CONSTRAINT CK_CARRERA_PERIOCIDAD CHECK (PERIODICIDAD IN('ANUAL','SEMESTRAL','SEMANAL','MENSUAL','DIARIMENTE'));
--------------------------------VERSION--------------------------------------------------------------------------------------
ALTER TABLE VERSION ADD CONSTRAINT CK_VERSION_IDMIEMBRO CHECK (ID_MIEMBRO BETWEEN 1 AND 99999);
--------------------------------SEGMENTO---------------------------------------------------------------------------------------
ALTER TABLE SEGMENTO ADD CONSTRAINT CK_SEGMENTO_NUMEROREGISTRO CHECK (NUMEROREGISTRO BETWEEN 1 AND 99999);
ALTER TABLE SEGMENTO ADD CONSTRAINT CK_SEGMENTO_TIPO CHECK (TIPO IN('C','M','L'));