/**CICLO1: CONSULTAS*/
/**<Consultar segmentos de montaña con secciones de descenso>*/
SELECT VERSION.NOMBRE,SEGMENTO.NOMBRE
FROM (VERSION JOIN SEGMENTO ON(VERSION.NOMBRESEGMENTO=SEGMENTO.NOMBRE))
WHERE TIPO='L';
/**<Consultar los cinco segmentos con tiempos mas cortos>*/
SELECT SEGMENTO.NOMBRE
FROM SEGMENTO JOIN REGISTRO ON(SEGMENTO.NUMEROREGISTRO=REGISTRO.NUMERO)
WHERE TIEMPO <=305555555;
/**<Consultar puntos de una carrera >*/
SELECT punto.nombre,carrera.nombre
FROM PUNTO JOIN CARRERA ON(PUNTO.CODIGOCA=CARRERA.CODIGO)
WHERE CARRERA.NOMBRE='VUELTA A COLOMBIA';
/**<Consultar la fecha  y pais de la version >*/
SELECT VERSION.FECHA,CARRERA.PAIS
FROM VERSION JOIN CARRERA ON(CARRERA.NOMBREVERSION=VERSION.NOMBRE);
/**<Consultar numero de registro de un ciclista >*/
SELECT REGISTRO.NUMERO
FROM REGISTRO JOIN CICLISTA ON(REGISTRO.NUMERO=ciclista.NUMEROREGISTRO)
WHERE CICLISTA.CATEGORIA=5;