CREATE TABLE CARRERA(
CODIGO VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(30)NOT NULL,
PAIS VARCHAR (15)NOT NULL,
CATEGORIA NUMBER(1)NOT NULL,
PERIODICIDAD VARCHAR(30)NOT NULL,
NOMBREVERSION VARCHAR(5));


CREATE TABLE PUNTO(
ORDEN NUMBER(2) NOT NULL,
NOMBRE VARCHAR(10)NOT NULL,
TIPO VARCHAR(1)NOT NULL,
DISTANCIA NUMBER(10,2)NOT NULL,
TIEMPOLIMITE NUMBER(9) NOT NULL,
CODIGOCA VARCHAR(20) NOT NULL,
NOMBRESEGMENTO VARCHAR(30)NOT NULL);


CREATE TABLE PROPIEDADDE(
PORCENTAJE NUMBER(2)NOT NULL,
CODIGOCA VARCHAR(20) NOT NULL,
IDMIEMBRO NUMBER(5) NOT NULL);


CREATE TABLE MIEMBRO(
ID NUMBER(5)NOT NULL,
IDT VARCHAR(2)NOT NULL,
IDN NUMBER(15)NOT NULL,
PAIS VARCHAR(15)NOT NULL,
CORREO VARCHAR(30)NOT NULL);


CREATE TABLE PERSONA(
NOMBRE VARCHAR(50)NOT NULL,
IDMIEMBRO NUMBER(5)NOT NULL,
RAZONSOCIAL VARCHAR(30)NOT NULL);


CREATE TABLE EMPRESA(
RAZONSOCIAL VARCHAR(30)NOT NULL,
IDMIEMBRO NUMBER(5)
);


CREATE TABLE CICLISTA(
NACIMIENTO DATE NOT NULL,
CATEGORIA NUMBER(1) NOT NULL,
IDMIEMBRO NUMBER(5)NOT NULL,
NUMEROREGISTRO NUMBER(3)NOT NULL);


CREATE TABLE PARTICIPA(
IDMIEMBRO NUMBER(5)NOT NULL,
NOMBREVERSION VARCHAR(5)NOT NULL
);

CREATE TABLE ORGANIZADO(
RAZONSOCIAL VARCHAR(30)NOT NULL,
NOMBREVERSION VARCHAR(5)NOT NULL
);


CREATE TABLE REGISTRO(
NUMERO NUMBER(3)NOT NULL,
FECHA DATE NOT NULL,
TIEMPO NUMBER(9) NOT NULL,
POSICION NUMBER(5)NOT NULL,
REVISION VARCHAR(50),
DIFICULTAD VARCHAR(1)NOT NULL,
FOTO VARCHAR(50),
COMENTARIO VARCHAR(30));


CREATE TABLE FOTO(
NUMEROREGISTRO NUMBER(3)NOT NULL,
FOTO VARCHAR(15)NOT NULL
);

CREATE TABLE VERSION(
NOMBRE VARCHAR (5)NOT NULL,
FECHA DATE NOT NULL,
NOMBRESEGMENTO VARCHAR(30)NOT NULL,
ID_MIEMBRO NUMBER(5)NOT NULL);


CREATE TABLE SEGMENTO(
NOMBRE VARCHAR(30)NOT NULL,
TIPO VARCHAR(1)NOT NULL,
NUMEROREGISTRO NUMBER(3)NOT NULL); 

