ALTER TABLE CARRERA ADD CONSTRAINT FK_CARRERA_VERSION FOREIGN KEY(NOMBREVERSION)REFERENCES VERSION(NOMBRE);
ALTER TABLE PUNTO ADD CONSTRAINT FK_PUNTO_CARRERA FOREIGN KEY (CODIGOCA)REFERENCES CARRERA(CODIGO);
ALTER TABLE PUNTO ADD CONSTRAINT FK_PUNTO_SEGMENTO FOREIGN KEY (NOMBRESEGMENTO)REFERENCES SEGMENTO(NOMBRE);
ALTER TABLE PROPIEDADDE ADD CONSTRAINT FK_PROPIEDAD_CARRERA FOREIGN KEY (CODIGOCA)REFERENCES CARRERA (CODIGO);
ALTER TABLE PROPIEDADDE ADD CONSTRAINT FK_PROPIEDAD_MIEMBRO FOREIGN KEY (IDMIEMBRO) REFERENCES MIEMBRO(ID);
ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMPRESA_PERSONA FOREIGN KEY(IDMIEMBRO)REFERENCES PERSONA(IDMIEMBRO);
ALTER TABLE EMPRESA ADD CONSTRAINT FK_EMPRESA_MIEMBRO FOREIGN KEY (IDMIEMBRO) REFERENCES MIEMBRO(ID);
ALTER TABLE PERSONA ADD CONSTRAINT FK_PERSONA_MIEMBRO FOREIGN KEY(IDMIEMBRO)REFERENCES MIEMBRO(ID);
ALTER TABLE CICLISTA ADD CONSTRAINT FK_CICLISTA_PERSONA FOREIGN KEY(IDMIEMBRO)REFERENCES PERSONA(IDMIEMBRO);
ALTER TABLE CICLISTA ADD CONSTRAINT FK_CICLISTA_REGISTRO FOREIGN KEY(NUMEROREGISTRO)REFERENCES REGISTRO(NUMERO);
ALTER TABLE PARTICIPA ADD CONSTRAINT FK_PARTICIPA_CICLISTA FOREIGN KEY (IDMIEMBRO)REFERENCES CICLISTA(IDMIEMBRO);
ALTER TABLE PARTICIPA ADD CONSTRAINT FK_PARTICIPA_VERSION FOREIGN KEY (NOMBREVERSION) REFERENCES VERSION(NOMBRE);
ALTER TABLE ORGANIZADO ADD CONSTRAINT FK_ORGANIZADO_EMPRESA FOREIGN KEY (RAZONSOCIAL) REFERENCES EMPRESA(RAZONSOCIAL);
ALTER TABLE ORGANIZADO ADD CONSTRAINT FK_ORGANIZADO_VERSION FOREIGN KEY (NOMBREVERSION) REFERENCES VERSION(NOMBRE);
ALTER TABLE VERSION ADD CONSTRAINT FK_VERSION_SEGMENTO FOREIGN KEY (NOMBRESEGMENTO) REFERENCES SEGMENTO(NOMBRE);
ALTER TABLE VERSION ADD CONSTRAINT FK_VERSION_CICLISTA FOREIGN KEY (ID_MIEMBRO) REFERENCES CICLISTA (IDMIEMBRO);
ALTER TABLE SEGMENTO ADD CONSTRAINT FK_SEGMENTO_REGISTRO FOREIGN KEY (NUMEROREGISTRO) REFERENCES REGISTRO(NUMERO);
ALTER TABLE FOTO ADD CONSTRAINT FK_FOTO_REGISTRO FOREIGN KEY (NUMEROREGISTRO) REFERENCES REGISTRO(NUMERO);

