INSERT INTO MIEMBRO(ID,IDT,IDN,PAIS,CORREO)VALUES(78,'CC',100116936444444,'COLOMBIA','SAAGULAICUHOTMAIL.COM');
INSERT INTO REGISTRO (NUMERO,FECHA,TIEMPO,POSICION,REVISION,DIFICULTAD,FOTO,COMENTARIO) VALUES (200,TO_DATE('2017-05-14','YYYY-MM-DD'),207777777,1,'BIEN','A','MONTAÑA.PDF','NO HUBO ACCIDENTES');
INSERT INTO SEGMENTO (NOMBRE,TIPO,NUMEROREGISTRO)VALUES('ETAPA 6','p',340);
INSERT INTO CARRERA(CODIGO,NOMBRE,PAIS,CATEGORIA,PERIODICIDAD,NOMBREVERSION)VALUES('414CUUUUUUUUUUUUUUUU','VUELTA A COLOMBIA','COLOMBIA',5,'diario', '202PE');
INSERT INTO PUNTO (ORDEN,NOMBRE,TIPO,DISTANCIA,TIEMPOLIMITE,CODIGOCA,NOMBRESEGMENTO)VALUES(18,'PUNTO 7','V',35,354444444,'414CUUUUUUUUUUUU','ETAPA 6' );