-----------------MIEMBRO------------------------------------------------------
INSERT INTO MIEMBRO(ID,IDT,IDN,PAIS,CORREO)VALUES(788,'CC',100116936444444,'COLOMBIA','SAAGULAICU@HOTMAIL.COM');
INSERT INTO MIEMBRO(ID,IDT,IDN,PAIS,CORREO)VALUES(888,'CC',100116936511111,'COLOMBIA','SAAGULAIC@HOTMAIL.COM');
INSERT INTO MIEMBRO(ID,IDT,IDN,PAIS,CORREO)VALUES(988,'CC',100116936655555,'COLOMBIA','SAAGULAI@HOTMAIL.COM');
------------------PERSONA----------------------------------------------------
INSERT INTO PERSONA(NOMBRE,IDMIEMBRO,RAZONSOCIAL)VALUES('SANTIAGO LAITON',788,'COLPATRIA');
INSERT INTO PERSONA(NOMBRE,IDMIEMBRO,RAZONSOCIAL)VALUES('SANTIAGO LAITON',988,'COLPATRIA');
INSERT INTO PERSONA(NOMBRE,IDMIEMBRO,RAZONSOCIAL)VALUES('SANTIAGO LAITON',888,'COLPATRIA');
----------------EMPRESA-------------------------------------------------------
INSERT INTO EMPRESA(RAZONSOCIAL,IDMIEMBRO)VALUES('COMSILAS.A.S',788);
INSERT INTO EMPRESA(RAZONSOCIAL,IDMIEMBRO)VALUES('COSTA.A.S',888);
INSERT INTO EMPRESA(RAZONSOCIAL,IDMIEMBRO)VALUES('METRO.A.S',988);
------------------REGISTRO----------------------------------------------------
INSERT INTO REGISTRO (NUMERO,FECHA,TIEMPO,POSICION,REVISION,DIFICULTAD,FOTO,COMENTARIO) VALUES (200,TO_DATE('2017-05-14','YYYY-MM-DD'),207777777,1,'BIEN','A','www.MONTAÑA.PDF','NO HUBO ACCIDENTES');
INSERT INTO REGISTRO (NUMERO,FECHA,TIEMPO,POSICION,REVISION,DIFICULTAD,FOTO,COMENTARIO) VALUES (250,TO_DATE('2017-05-14','YYYY-MM-DD'),401111111,1,'BIEN','M','www.MONTAÑA.PDF','NO HUBO ACCIDENTE');
INSERT INTO REGISTRO (NUMERO,FECHA,TIEMPO,POSICION,REVISION,DIFICULTAD,FOTO,COMENTARIO) VALUES (340,TO_DATE('2017-05-14','YYYY-MM-DD'),305555555,1,'BIEN','B','www.MONTAÑA.GIF','NO ACCIDENTES');
------------------CICLISTA---------------------------------------------------
INSERT INTO CICLISTA(NACIMIENTO,CATEGORIA,IDMIEMBRO,NUMEROREGISTRO)VALUES(TO_DATE('27/02/2000','DD/MM/YYYY'),5,788,200);
INSERT INTO CICLISTA(NACIMIENTO,CATEGORIA,IDMIEMBRO,NUMEROREGISTRO)VALUES(TO_DATE('27/02/2000','DD/MM/YYYY'),4,888,250);
INSERT INTO CICLISTA(NACIMIENTO,CATEGORIA,IDMIEMBRO,NUMEROREGISTRO)VALUES(TO_DATE('27/02/2000','DD/MM/YYYY'),5,988,340);
------------------SEGMENTO----------------------------------------------------
INSERT INTO SEGMENTO (NOMBRE,TIPO,NUMEROREGISTRO)VALUES('ETAPA 1','M',200);
INSERT INTO SEGMENTO (NOMBRE,TIPO,NUMEROREGISTRO)VALUES('ETAPA 4','C',250);
INSERT INTO SEGMENTO (NOMBRE,TIPO,NUMEROREGISTRO)VALUES('ETAPA 6','L',340);
------------------FOTOS-----------------------------------------------------
INSERT INTO FOTO (NUMEROREGISTRO,FOTO) VALUES (200,'www.MONTAÑA.PDF');
INSERT INTO FOTO (NUMEROREGISTRO,FOTO) VALUES (250,'www.PLANO.GIF');
INSERT INTO FOTO (NUMEROREGISTRO,FOTO) VALUES (340,'www.MIXTO.PDF');
------------------VERSION----------------------------------------------------
INSERT INTO VERSION (NOMBRE,FECHA,NOMBRESEGMENTO,ID_MIEMBRO)VALUES('201CO',TO_DATE('2012-06-24','YYYY-MM-DD'),'ETAPA 1',788);
INSERT INTO VERSION (NOMBRE,FECHA,NOMBRESEGMENTO,ID_MIEMBRO)VALUES('202BA',TO_DATE('2012-06-24','YYYY-MM-DD'),'ETAPA 4',888);
INSERT INTO VERSION (NOMBRE,FECHA,NOMBRESEGMENTO,ID_MIEMBRO)VALUES('202PE',TO_DATE('2012-06-24','YYYY-MM-DD'),'ETAPA 6',988);
--------------------PARTICIPA----------------------------------------------
INSERT INTO PARTICIPA(IDMIEMBRO,NOMBREVERSION)VALUES(788,'201CO');
INSERT INTO PARTICIPA(IDMIEMBRO,NOMBREVERSION)VALUES(888,'202BA');
INSERT INTO PARTICIPA(IDMIEMBRO,NOMBREVERSION)VALUES(988,'202PE');
------------------ORGANIZADO------------------------------------------------
INSERT INTO ORGANIZADO (RAZONSOCIAL,NOMBREVERSION)VALUES('COMSILAS.A.S','201CO');
INSERT INTO ORGANIZADO (RAZONSOCIAL,NOMBREVERSION)VALUES('COSTA.A.S','202BA');
INSERT INTO ORGANIZADO (RAZONSOCIAL,NOMBREVERSION)VALUES('METRO.A.S','202PE');
--------------------CARRERA--------------------------------------------------
INSERT INTO CARRERA(CODIGO,NOMBRE,PAIS,CATEGORIA,PERIODICIDAD,NOMBREVERSION)VALUES('123ABBBBBBBBBBBBBBBB','TOUR F','FRANCIA',2,'ANUAL', '201CO');
INSERT INTO CARRERA(CODIGO,NOMBRE,PAIS,CATEGORIA,PERIODICIDAD,NOMBREVERSION)VALUES('443REEEEEEEEEEEEEEEE','VUELTA A ESPAÃ‘A','ESPANA',4,'SEMANAL', '202BA');
INSERT INTO CARRERA(CODIGO,NOMBRE,PAIS,CATEGORIA,PERIODICIDAD,NOMBREVERSION)VALUES('414CUUUUUUUUUUUUUUUU','VUELTA A COLOMBIA','COLOMBIA',5,'MENSUAL', '202PE');
-------------------PUNTO-----------------------------------------------------
INSERT INTO PUNTO (ORDEN,NOMBRE,TIPO,DISTANCIA,TIEMPOLIMITE,CODIGOCA,NOMBRESEGMENTO)VALUES(10,'PUNTO 3','P',15,154555555,'123ABBBBBBBBBBBBBBBB','ETAPA 1' );
INSERT INTO PUNTO (ORDEN,NOMBRE,TIPO,DISTANCIA,TIEMPOLIMITE,CODIGOCA,NOMBRESEGMENTO)VALUES(8,'PUNTO 5','H',21,154555555,'443REEEEEEEEEEEEEEEE','ETAPA 4' );
INSERT INTO PUNTO (ORDEN,NOMBRE,TIPO,DISTANCIA,TIEMPOLIMITE,CODIGOCA,NOMBRESEGMENTO)VALUES(18,'PUNTO 7','V',35,354444444,'414CUUUUUUUUUUUUUUUU','ETAPA 6' );
--------------------PROPIEDADDE----------------------------------------------
INSERT INTO PROPIEDADDE(PORCENTAJE,CODIGOCA,IDMIEMBRO)VALUES(50,'123ABBBBBBBBBBBBBBBB',788);
INSERT INTO PROPIEDADDE(PORCENTAJE,CODIGOCA,IDMIEMBRO)VALUES(40,'443REEEEEEEEEEEEEEEE',888);
INSERT INTO PROPIEDADDE(PORCENTAJE,CODIGOCA,IDMIEMBRO)VALUES(90,'414CUUUUUUUUUUUUUUUU',988);