ALTER TABLE CARRERA ADD CONSTRAINT PK_CARRERA PRIMARY KEY (CODIGO);
ALTER TABLE PUNTO ADD CONSTRAINT PK_PUNTO PRIMARY KEY (CODIGOCA);
ALTER TABLE MIEMBRO ADD CONSTRAINT PK_MIEMBRO PRIMARY KEY(ID);
ALTER TABLE PERSONA ADD CONSTRAINT PK_PERSONA PRIMARY KEY(IDMIEMBRO);
ALTER TABLE EMPRESA ADD CONSTRAINT PK_EMPRESA PRIMARY KEY (RAZONSOCIAL);
ALTER TABLE CICLISTA ADD CONSTRAINT PF_CICLISTA PRIMARY KEY (IDMIEMBRO);
ALTER TABLE REGISTRO ADD CONSTRAINT PK_REGISTRA PRIMARY KEY (NUMERO);
ALTER TABLE VERSION ADD CONSTRAINT PF_VERSION PRIMARY KEY (NOMBRE);
ALTER TABLE SEGMENTO ADD CONSTRAINT PF_NOMBRE PRIMARY KEY (NOMBRE);



