------------CRUD ACCIDENTES ------------
DROP TRIGGER TR_ACCIDENTE_NO;
DROP TRIGGER TR_ACCIDENTE_FECHAINI;
DROP TRIGGER TR_MOD_DETALLES;
DROP TRIGGER TR_MOD_FECHA;
DROP TRIGGER TR_ELI_DETALLES;
----------CRUD POLIZA-------------------
DROP TRIGGER TR_POLIZA_NO;
DROP TRIGGER TR_POLIZA_FECHAINI;
DROP TRIGGER TR_POLIZAS_FECHAFIN;
DROP TRIGGER TR_POLIZAS_ELIMINACION;
----------OTROS ------------------------
DROP TRIGGER TR_ELIMINAR_ABOGADOS;
DROP TRIGGER TR_ELIMINAR_VEHICULOS;
DROP TRIGGER TR_ELIMINAR_conductores;
DROP TRIGGER TR_ELIMINAR_LOTES;
DROP TRIGGER MOD_TARJETA_IDENTIFICACION;
DROP TRIGGER TR_ELIMINAR_FRENOS;
DROP TRIGGER TR_ELIMINAR_AIRBAGS;
DROP TRIGGER TR_ELIMINAR_CONTROLES;
