ALTER TABLE VEHICULOS DROP CONSTRAINT FK_VEHICULO_CONDUCTOR;
ALTER TABLE VEHICULOS ADD CONSTRAINT FK_VEHICULO_CONDUCTOR FOREIGN KEY(CECONDUCTOR) REFERENCES CONDUCTORES(CEDULA)ON DELETE CASCADE;
ALTER TABLE POLIZAS DROP CONSTRAINT FK_POLIZA_VEHICULO;
ALTER TABLE POLIZAS ADD CONSTRAINT FK_POLIZA_VEHICULO FOREIGN KEY(NOMOTOR)REFERENCES VEHICULOS(NOMOTOR)ON DELETE CASCADE;
-------------------------------------ACCIONESOK----------------------------------------------------------------------------------------
delete from vehiculos where nomotor = 766;
